In [1]:
import sys
main_path = "../.."
sys.path.append(main_path)

import numpy as np
import pandas as pd
from impyute.imputation.cs import fast_knn
import os
import yaml
import copy

In [2]:
# data = pd.read_csv(f'{main_path}/data/raw/lung_cancer.csv', sep="\t", encoding = "ISO-8859-1")
data = pd.read_excel('../../data/raw/lung_cancer.xlsx')
# print(data)
xlsx = pd.ExcelFile('../../data/raw/lung_cancer.xlsx')

# Sayfa adlarını yazdırın
df1 = pd.read_excel(xlsx, sheet_name='akciğer')
df2 = pd.read_excel(xlsx, sheet_name='kontrol')

emptyLiveMonth = 180
# print(df2.iloc[:][3:len(df2)])
df2 = df2.iloc[:][3:len(df2)]
df2 = df2.iloc[:,5:22]
data = data.iloc[:][3:len(data)]
# data = np.delete(data, np.s_[2:6], axis=1)
binary_data = np.where(pd.isna(np.ravel(data.iloc[:,2])), 0, np.ravel(data.iloc[:,2]))
data_live_month = np.where(pd.isna(np.ravel(data.iloc[:,5])), emptyLiveMonth, np.ravel(data.iloc[:,5]))
print(data_live_month)
# data_binary_tree[np.isnan(data_binary_tree)] = 1

data = data.drop(['Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5'], axis=1)
data = data.iloc[:,5:22]

# print(data.iloc[:,5:22])
# print(np.delete(data, np.s_[2:6], axis=1))
# data = pd.DataFrame(data)
# data = np.concatenate(data, df2)

# data = np.concatenate(data, df2)
# print(data.iloc[:,9])

targets = np.ravel(data.iloc[:,0])
# print(targets)
targets = np.where(targets == 'kontrol', 0, 1)
# print(targets)

data = pd.concat([data, df2])
data = pd.DataFrame(data)

features = np.array(data.iloc[:,2:17])
columns = data.columns[2:17]
targets_control = np.ravel(df2.iloc[:,0])
binary_data_control = [1 for i in range(len(targets_control))]
# data_live_month_control = [emptyLiveMonth for i in range(len(targets_control))]

binary_data = np.concatenate([binary_data, binary_data_control])
# data_live_month = np.concatenate([data_live_month, data_live_month_control])
targets_control = np.where(targets_control == 'kontrol', 0, 1)
# print(targets)

features_control = np.array(df2.iloc[:,2:17])
columns_control = df2.columns[2:17]
targets = np.concatenate([targets, targets_control])
# features = np.concatenate([features, features_control])
# columns = np.concatenate([columns, columns])

with open(f'{main_path}/config.yaml', 'r') as f:
    config = yaml.safe_load(f)
    
decimal_forms = config['decimal']
# print(features)

df_path = f"{main_path}/data/processed/dataframes"
os.makedirs(df_path, exist_ok=True)
data = data.iloc[:,2:17]
print(data.iloc[:,2:17])

[125 7 59 72 147 25 96 9 30 68 26 146 7 100 14 180 54 15 103 5 64 152 117
 151 121 0 117 29 180 37 22 35 31 35 16 45 154 2 23 180 99 152 180 117 180
 152 41 34 17 119 17 101 16 117 91 102 180 180 137 180 116 81 24 120 32
 180 33 146 83 104]
   p16580 FOXP3 ICAM-1 GALECTİN-3 CD28 GALECTİN-3.1 CD27 PD1/pdcd1PDL1/cd274   
3      CC    CC     AG         AC   TT           CA   TT                  CT  \
4      CC    CC     AG         CC   TT           AA   AA                  CC   
5      CC    AA     AG         AA   TT           CC   AA                  CT   
6     NaN    AA     AG         AC   CT           CC   AA                  CT   
7      CC   NaN     AG        NaN   TT          NaN   AT                  CT   
..    ...   ...    ...        ...  ...          ...  ...                 ...   
68     CC    CC     GG         CC   CC          NaN   AA                  CT   
69     CC    CC     AA         AA   TT           CC   TT                  CC   
70     CT    CC     GG         AC   TT 

In [3]:
pd.DataFrame(binary_data, columns=['is_live']).to_csv(f"{df_path}/binary_data_is_live.csv", index=False)

In [4]:
print(data_live_month)
categorized_data_live_month_18 = []
categorized_data_live_month_36 = []
categorized_data_live_month_54 = []
categorized_data_live_month_72 = []
categorized_data_live_month_90 = []
categorized_data_live_month_108 = []

for num in data_live_month:
    if num >= 0 and num <= 18:
        categorized_data_live_month_18.append(0)
    else:
        categorized_data_live_month_18.append(1)

for num in data_live_month:
    if num >= 0 and num <= 36:
        categorized_data_live_month_36.append(0)
    else:
        categorized_data_live_month_36.append(1)

for num in data_live_month:
    if num >= 0 and num <= 54:
        categorized_data_live_month_54.append(0)
    else:
        categorized_data_live_month_54.append(1)

for num in data_live_month:
    if num >= 0 and num <= 72:
        categorized_data_live_month_72.append(0)
    else:
        categorized_data_live_month_72.append(1)


for num in data_live_month:
    if num >= 0 and num <= 90:
        categorized_data_live_month_90.append(0)
    else:
        categorized_data_live_month_90.append(1)


for num in data_live_month:
    if num >= 0 and num <= 108:
        categorized_data_live_month_108.append(0)
    else:
        categorized_data_live_month_108.append(1)



pd.DataFrame(categorized_data_live_month_18, columns=['live_month']).to_csv(f"{df_path}/data_live_month_18.csv", index=False)
pd.DataFrame(categorized_data_live_month_36, columns=['live_month']).to_csv(f"{df_path}/data_live_month_36.csv", index=False)
pd.DataFrame(categorized_data_live_month_54, columns=['live_month']).to_csv(f"{df_path}/data_live_month_54.csv", index=False)
pd.DataFrame(categorized_data_live_month_72, columns=['live_month']).to_csv(f"{df_path}/data_live_month_72.csv", index=False)
pd.DataFrame(categorized_data_live_month_90, columns=['live_month']).to_csv(f"{df_path}/data_live_month_90.csv", index=False)
pd.DataFrame(categorized_data_live_month_108, columns=['live_month']).to_csv(f"{df_path}/data_live_month_108.csv", index=False)

[125 7 59 72 147 25 96 9 30 68 26 146 7 100 14 180 54 15 103 5 64 152 117
 151 121 0 117 29 180 37 22 35 31 35 16 45 154 2 23 180 99 152 180 117 180
 152 41 34 17 119 17 101 16 117 91 102 180 180 137 180 116 81 24 120 32
 180 33 146 83 104]


### Baseline Approach

In [5]:
# baseline_data = data[['mdm2', 'GAL3', 'TIM1', 'p16540', 'p16580']]    
baseline_data = data[['IDO-1', 'p16540', 'p16580', 'FOXP3', 'ICAM-1', 'GALECTİN-3', 'CD27', 'PD1/pdcd1PDL1/cd274', 'PDL1', 'CD40', 'TIM1','CTLA-4', 'MDM2']]
one_hot_baseline = pd.get_dummies(baseline_data)
print()
one_hot_baseline.to_csv(f"{df_path}/baseline_approach.csv", index=False)
print(targets)
pd.DataFrame(targets, columns=['target']).to_csv(f"{df_path}/targets.csv", index=False)


[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


### One-Hot Encoding (on categorical data) -> Data Imputation

In [6]:
# ohe = pd.get_dummies(data.iloc[:,3:13][2:117])
ohe = pd.get_dummies(data)
print(data)
print(ohe)
for clm in columns:
    ohe.loc[data[clm].isnull(), ohe.columns.str.startswith("{}_".format(clm))] = np.nan

   IDO-1 p16540 p16580 FOXP3 ICAM-1 GALECTİN-3 CD28 GALECTİN-3.1 CD27   
3     CC     CC     CC    CC     AG         AC   TT           CA   TT  \
4     CC     CC     CC    CC     AG         CC   TT           AA   AA   
5    NaN     CG     CC    AA     AG         AA   TT           CC   AA   
6     CC    NaN    NaN    AA     AG         AC   CT           CC   AA   
7    NaN     CC     CC   NaN     AG        NaN   TT          NaN   AT   
..   ...    ...    ...   ...    ...        ...  ...          ...  ...   
68   NaN     CG     CC    CC     GG         CC   CC          NaN   AA   
69   NaN     CG     CC    CC     AA         AA   TT           CC   TT   
70   NaN     CG     CT    CC     GG         AC   TT          NaN   AT   
71    GC     CC     CC    CA    NaN         CC  NaN           AA   AA   
72    GG    NaN    NaN    CA    NaN         AC   TT           CA   AT   

   PD1/pdcd1PDL1/cd274 PDL1 CD40 TIM1 CTLA-4 MDM2  
3                   CT   AA   CC   CC     AA   TT  
4                  

In [7]:
# ohe['age'].fillna(0.0)
ohe = ohe.astype(float)
df = pd.DataFrame(ohe, columns =['age'])
  
# Apply the function
# ohe['age'] = df['age'].fillna(0)
  
print((ohe.values))
ohe_di = fast_knn(ohe.values, k=30)
ohe_di_df = pd.DataFrame(ohe_di, columns=ohe.columns)
ohe_di_df.to_csv(f"{df_path}/ohe_di.csv", index=False)

[[ 1.  0.  0. ...  0.  0.  1.]
 [ 1.  0.  0. ...  0.  1.  0.]
 [nan nan nan ...  0.  1.  0.]
 ...
 [nan nan nan ...  0.  1.  0.]
 [ 0.  1.  0. ...  1.  0.  0.]
 [ 0.  0.  1. ... nan nan nan]]


### One-Hot Encoding (on categorical data) -> Data Imputation -> Float to Int

In [8]:
sys.setrecursionlimit(100000) #Increase the recursion limit of the OS
# K-nn implementation gives us float values and we convert it to nearest integer
ohe_di_fi = np.round(ohe_di).astype('int')

ohe_di_fi_df = pd.DataFrame(ohe_di_fi, columns=ohe.columns)
ohe_di_fi_df.to_csv(f"{df_path}/ohe_di_fi.csv", index=False)

### Custom Data Transformation (CDT) -> Data Imputation

In [9]:
cdt = pd.DataFrame(features)
print(columns)
cdt.columns = columns
# print(cdt.columns, cdt['p16580'], decimal_forms)

for col in cdt.columns:
    cdt[col] = cdt[col].map(decimal_forms)

print(cdt.values)


Index(['IDO-1', 'p16540', 'p16580', 'FOXP3', 'ICAM-1', 'GALECTİN-3', 'CD28',
       'GALECTİN-3.1', 'CD27', 'PD1/pdcd1PDL1/cd274', 'PDL1', 'CD40', 'TIM1',
       'CTLA-4', 'MDM2'],
      dtype='object')
[[10. 10. 10. ... 10.  0.  5.]
 [10. 10. 10. ... 14.  0. nan]
 [nan nan 10. ... 10.  0. nan]
 ...
 [nan nan  9. ... 10. nan nan]
 [14. 10. 10. ... 10. nan 15.]
 [15. nan nan ... 10.  0. nan]]


In [10]:
sys.setrecursionlimit(100000) #Increase the recursion limit of the OS

print(cdt)

cdt_di = fast_knn(cdt.values, k=30)

cdt_di_df = pd.DataFrame(cdt_di, columns=columns)
cdt_di_df.to_csv(f"{df_path}/cdt_di.csv", index=False)

     IDO-1  p16540  p16580  FOXP3  ICAM-1  GALECTİN-3  CD28  GALECTİN-3.1   
0     10.0    10.0    10.0   10.0     NaN         2.0   5.0           8.0  \
1     10.0    10.0    10.0   10.0     NaN        10.0   5.0           0.0   
2      NaN     NaN    10.0    0.0     NaN         0.0   5.0          10.0   
3     10.0     NaN     NaN    0.0     NaN         2.0   9.0          10.0   
4      NaN    10.0    10.0    NaN     NaN         NaN   5.0           NaN   
..     ...     ...     ...    ...     ...         ...   ...           ...   
135    NaN     NaN    10.0   10.0    15.0        10.0  10.0           NaN   
136    NaN     NaN    10.0   10.0     0.0         0.0   5.0          10.0   
137    NaN     NaN     9.0   10.0    15.0         2.0   5.0           NaN   
138   14.0    10.0    10.0    8.0     NaN        10.0   NaN           0.0   
139   15.0     NaN     NaN    8.0     NaN         2.0   5.0           8.0   

     CD27  PD1/pdcd1PDL1/cd274  PDL1  CD40  TIM1  CTLA-4  MDM2  
0     5.0 

### Custom Data Transformation -> Data Imputation -> Float to Int

In [11]:
cdt_di_fi = np.round(cdt_di).astype('int')
cdt_di_fi_df = pd.DataFrame(cdt_di_fi, columns=columns)
cdt_di_fi_df.to_csv(f"{df_path}/cdt_di_fi.csv", index=False)

### Custom Data Transformation -> Data Imputation -> One Hot Encoding

In [12]:
cdt_di_ohe_df = pd.get_dummies(cdt_di_df, sparse=True, columns=columns)
cdt_di_ohe_df.to_csv(f"{df_path}/cdt_di_ohe.csv", index=False)

### Custom Data Transformation (CDT) -> Data Imputation -> Float to Int -> One-Hot Encoding

In [15]:
cdt_di_fi_ohe_df = pd.get_dummies(cdt_di_fi_df.astype('str'), sparse=True, columns=columns)

cdt_di_fi_ohe_df.to_csv(f"{df_path}/cdt_di_fi_ohe.csv", index=False)

Index(['IDO-1', 'p16540', 'p16580', 'FOXP3', 'ICAM-1', 'GALECTİN-3', 'CD28',
       'GALECTİN-3.1', 'CD27', 'PD1/pdcd1PDL1/cd274', 'PDL1', 'CD40', 'TIM1',
       'CTLA-4', 'MDM2'],
      dtype='object')
Index(['IDO-1_10', 'IDO-1_14', 'IDO-1_15', 'p16540_10', 'p16540_11',
       'p16540_15', 'p16580_10', 'p16580_5', 'p16580_9', 'FOXP3_0', 'FOXP3_10',
       'FOXP3_7', 'FOXP3_8', 'ICAM-1_0', 'ICAM-1_15', 'ICAM-1_5', 'ICAM-1_6',
       'GALECTİN-3_0', 'GALECTİN-3_10', 'GALECTİN-3_2', 'GALECTİN-3_4',
       'GALECTİN-3_5', 'CD28_10', 'CD28_5', 'CD28_6', 'CD28_7', 'CD28_9',
       'GALECTİN-3.1_0', 'GALECTİN-3.1_10', 'GALECTİN-3.1_2', 'GALECTİN-3.1_3',
       'GALECTİN-3.1_4', 'GALECTİN-3.1_5', 'GALECTİN-3.1_6', 'GALECTİN-3.1_7',
       'GALECTİN-3.1_8', 'CD27_0', 'CD27_1', 'CD27_5',
       'PD1/pdcd1PDL1/cd274_10', 'PD1/pdcd1PDL1/cd274_5',
       'PD1/pdcd1PDL1/cd274_8', 'PD1/pdcd1PDL1/cd274_9', 'PDL1_0', 'PDL1_1',
       'PDL1_10', 'PDL1_2', 'CD40_10', 'CD40_5', 'CD40_9', 'TIM1_10',
     

# Sources:

- https://towardsdatascience.com/the-use-of-knn-for-missing-values-cf33d935c637